// Copyright (C) 2026, NTT, Inc.

=== リソースの設定

本マニュアルとセットで提供されるPG-REX用の『pm_pcsgen環境定義書』を用いて、クラスタ内のリソース構成、動作条件、パラメータ、配置制約などを設定します。 +
設定した『pm_pcsgen環境定義書』は、pm_extra_toolsに同梱されているpm_pcsgenコマンドを使用して、リソース定義xmlファイルを作成します。

==== リソース定義xmlファイル作成手順の概要

PG-REXでのリソース定義xmlファイル作成の手順は以下のとおりです。

. PG-REX用の『pm_pcsgen環境定義書』を編集する。
. 編集した『pm_pcsgen環境定義書』をcsvファイル形式に変換し、pgrex01に転送する。
. pgrex01上でpm_pcsgenコマンドを使用し、csvファイルをxmlファイルに変換する。

作成したリソース定義xmlファイルを運用補助ツールあるいはpcsコマンドを使用してPacemakerに読みませることで、ファイルの内容が反映されます。 +
以降、『pm_pcsgen環境定義書』で、環境に合わせて設定する必要がある項目を説明します。各項目の設定内容は、本マニュアルで用いている設定を示しています。


==== 仮想IPアドレス(Primary側)の設定

『pm_pcsgen環境定義書』の表7-1-1にPostgreSQLのPrimary側接続用の仮想IPアドレスの設定を行います。

.PG-REXにおけるPostgreSQLのPrimary側接続用仮想IPアドレスの設定
[%autowidth]
|===
|項目 |設定内容 |説明

|ip
|`+192.168.0.10+`
|PostgreSQLのPrimary側接続用仮想IPアドレスを設定する。

|nic
|`+bond0+`
|PostgreSQLのPrimary側接続用デバイス名を設定する。

|cidr_netmask
|`+24+`
|PostgreSQLのPrimary側接続用ネットマスクを設定する。
|===

『pm_pcsgen環境定義書』の表7-1-2にDBレプリケーション受付用の仮想IPアドレスの設定を行います。

.PG-REXにおけるDBレプリケーション受付用仮想IPアドレスの設定
[%autowidth]
|===
|項目 |設定内容 |説明

|ip
|`+192.168.2.3+`
|DBレプリケーション受付用仮想IPアドレスを設定する。

|nic
|`+bond1+`
|DBレプリケーション受付用デバイス名を設定する。

|cidr_netmask
|`+24+`
|DBレプリケーション受付用ネットマスクを設定する。
|===

==== PostgreSQLの設定

『pm_pcsgen環境定義書』の表7-1-3にPostgreSQLの設定を行います。

.PG-REXにおけるPostgreSQL制御の設定
[%autowidth]
|===
|項目 |設定内容 |説明

|node_list
|`+pgrex01 pgrex02+`
|HAクラスタを構成するノードの名前を設定する。(ノードの名前の間はスペース区切り)

|master_ip
|`+192.168.2.3+`
|『pm_pcsgen環境定義書』の表7-1-2に設定したレプリケーション受付用の仮想IPアドレスを設定する。

|restore_command
|`+/bin/cp /dbfp/pgarch/arc1/%f %p+`

|アーカイブディレクトリからWALファイルをリストアするためのコマンドを設定する。
アーカイブコマンドに対応したコマンドを設定すること。 +

(参考) +
アーカイブコマンドでgzipを使用した場合はリストアコマンドにもgzipを使用すること。 +
コマンド設定例を以下に示す。 +
`+'/bin/gzip -cd /dbfp/pgarch/arc1/%f.gz > %p'+` +

アーカイブコマンドの設定は『 <<_postgresql_confの編集,postgresql_confの編集>> 』を参照してください。

|repuser
|`+repuser+`
|『 <<_レプリケーションユーザの作成,レプリケーションユーザの作成>> 』で作成したレプリケーションユーザを設定する。
|===

==== ネットワーク監視の設定

『pm_pcsgen環境定義書』の表7-2-1にネットワーク監視の設定を行います。なお、PG-REXではS-LANを監視します。監視するネットワークのIPアドレスとしてS-LANのデフォルトゲートウェイ等を設定してください。

.PG-REXにおけるネットワーク監視の設定
[%autowidth]
|===
|項目 |設定内容 |説明

|host_list
|`+192.168.0.254+`
|監視するネットワークのIPアドレス。PING監視先(GW等)用に用意したアドレスを設定する。
|===

==== ディスク監視の設定

『pm_pcsgen環境定義書』の表7-3-1にディスク監視の設定を行います。なお、PG-REXでは、OS起動ディスク、DBクラスタ、WAL、アーカイブログを格納するディスクを監視します。

.PG-REXにおけるディスク監視の設定
[%autowidth]
|===
|項目 |設定内容 |説明

|drives
|`+/dev/sda /dev/sdb+`
|検査対象とするディスクのデバイス名を空白文字で区切って列挙する

|io_timeout
|`+10+`
|ディスク故障発生とみなすディスクI/Oのタイムアウト時間を設定する +
デフォルト値は10(単位秒)
|===

==== STONITHの設定

『pm_pcsgen環境定義書』の表8-1-1、表8-1-2、表9-1にSTONITHの設定を行います。

.pgrex01用STONITH(表8-1-1)の設定
[%autowidth]
|===
|項目 |設定内容 |説明

|pcmk_host_list
|`+pgrex01+`
|STONITH対象ノードのホスト名(uname -nの結果)

|ip
|`+172.20.144.43+`
|HW制御ボード接続用IPアドレス

|username
|`+Administrator+`
|HW制御ボード接続用ユーザID

|password
|
|HW制御ボード接続用パスワード
|===


.pgrex02用STONITH(表8-1-2)の設定
[%autowidth]
|===
|項目 |設定内容 |説明

|pcmk_host_list
|`+pgrex02+`
|STONITH対象ノードのホスト名(uname -nの結果)

|ip
|`+172.20.144.44+`
|HW制御ボード接続用IPアドレス

|username
|`+Administrator+`
|HW制御ボード接続用ユーザID

|password
|
|HW制御ボード接続用パスワード
|===

.STONITHのリソース配置制約(表9-1)の設定
[%autowidth]
|===
|リソースID |ノード |説明

|fence1-ipmilan
|pgrex01
|『pm_pcsgen環境定義書』の表8-1-1のpcmk_host_listの設定内容

|fence2-ipmilan
|pgrex02
|『pm_pcsgen環境定義書』の表8-1-2のpcmk_host_listの設定内容
|===

==== 仮想IPアドレス(Standby側)の設定

Standbyへのデータベース接続を利用する場合は、『pm_pcsgen環境定義書』の表7-1-StandbyにStandby側接続用の仮想IPアドレスの設定を行います。

.PG-REXにおけるPostgreSQLのStandby側接続用仮想IPアドレスの設定
[%autowidth]
|===
|項目 |設定内容 |説明

|ip
|`+192.168.0.20+`
|PostgreSQLのStandby側接続用仮想IPアドレスを設定する。

|nic
|`+bond0+`
|PostgreSQLのStandby側接続用デバイス名を設定する。

|cidr_netmask
|`+24+`
|PostgreSQLのStandby側接続用ネットマスクを設定する。
|===

Standbyへのデータベース接続を利用しない場合は、『pm_pcsgen環境定義書』のipaddr-standbyの設定をコメントアウト(シートのA列に「#」を記述)します。

具体的な設定位置は、以下のとおりです。

* 表4-1 ： リソースIDがipaddr-standbyの行
* 表7-1-Standby ： 表全体
* 表9-2 ： リソースIDがipaddr-standbyの行(条件属性名にpgsql-statusと記述されている行)

==== リソース定義xmlファイルの作成

以下の操作を行い、リソース定義xmlファイルを作成します。

本作業はrootユーザで行います。

. Microsoft^(R)^ Excelを使って『pm_pcsgen環境定義書』のシートを修正してCSV形式で保存します。 +
本マニュアルではファイル名は「pm_pcsgen_env.csv」とします。
. 保存したcsvファイル（pm_pcsgen_env.csv）を、pgrex01に転送します。 +
ファイル転送の際に文字コード変換を行わないよう注意してください。
. pm_pcsgenコマンドを実行するため、HAクラスタを作成し、corosync.confを作成します。
+
HAクラスタの作成には、HAクラスタ名、それぞれのノードのホスト名とインターコネクトLANのIPアドレス2つのセットを2組指定します。
+
....
# pcs cluster setup pgrex_cluster pgrex01 addr=192.168.1.1 addr=192.168.3.1 pgrex02 addr=192.168.1.2 addr=192.168.3.2
Destroying cluster on hosts: 'pgrex01', 'pgrex02'...
pgrex01: Successfully destroyed cluster
pgrex02: Successfully destroyed cluster
Requesting remove 'pcsd settings' from 'pgrex01', 'pgrex02'
pgrex01: successful removal of the file 'pcsd settings'
pgrex02: successful removal of the file 'pcsd settings'
Sending 'corosync authkey', 'pacemaker authkey' to 'pgrex01', 'pgrex02
pgrex01: successful distribution of the file 'corosync authkey'
pgrex01: successful distribution of the file 'pacemaker authkey'
pgrex02: successful distribution of the file 'corosync authkey'
pgrex02: successful distribution of the file 'pacemaker authkey'
Sending 'corosync.conf' to 'pgrex01', 'pgrex02'
pgrex01: successful distribution of the file 'corosync.conf'
pgrex02: successful distribution of the file 'corosync.conf'
Cluster has been successfully set up.
....
. pgrex01上で、pm_pcsgenコマンドを使用し、転送したcsvファイルをxmlファイルに変換します。 +
本マニュアルでは、変換後のファイル名を「pm_pcsgen_env.xml」とします。
+
....
# pm_pcsgen pm_pcsgen_env.csv
pm_pcsgen_env.xml (CIB), pm_pcsgen_env.sh (PCS) を出力しました。
....
+
NOTE: リソース定義xmlファイル生成時にリソース定義用スクリプトファイル(pm_pcsgen_env.sh)も生成されますが、本マニュアルでは利用しません。

<<<

