// Copyright (C) 2026, NTT, Inc.

== メンテナンス時の対応

本章は、PostgreSQLのバックアップ取得の操作手順、アーカイブログ削除の操作手順、およびPG-REX(PrimaryまたはStandby)の停止を伴うメンテナンス(PostgreSQLのマイナーバージョンアップやハードウェアの増設等の作業)時のノードの停止、起動手順について記述します。

作業を行う際には、記述されている手順以外は行なわない様にしてください。

=== PostgreSQLのバックアップ

PG-REXでは、PostgreSQL単独の場合と同じ方法で、Primaryからオンライン物理バックアップを取得することができます。しかし、バックアップ取得は、大量のI/Oを発生させる負荷の高い処理であるため、それがPrimaryで実行されるオンライン負荷に影響を与えないようにStandbyで取得することも可能です。

本節では、PostgreSQLのバックアップを取得する手順について記述します。

本節の作業は、postgresユーザで行います。


==== PostgreSQLのバックアップ

PostgreSQLのバックアップを取得する手順は、『 https://www.postgresql.jp/document/18/html/continuous-archiving.html#BACKUP-BASE-BACKUP[PostgreSQLドキュメント] 』
の手順に従い実施してください。また、フェイルオーバが発生した場合は、新Primaryからバックアップを取得し直してください。旧Primaryから取得したバックアップは使用できない可能性があります。

[NOTE]
====
以下のようなコマンドを実行することになります。ここでは、ipaddr-replicationを使用してPrimaryからバックアップを取得しています。

[source,subs="quotes"]
....
$ pg_basebackup -h _192.168.2.3_ -U repuser -D _/backupdirectory_ -X stream -P
....
====

==== その他のバックアップツールを使用する場合の注意事項

ここではpg_basebackup 以外のツールを用いてデータベースのバックアップを取得して使用する際の注意事項を説明します。


【バックアップツールの選択】 ::
アーカイブログが利用できるタイプのバックアップツールを選択してください。PG-REXではPostgreSQLの継続的アーカイブ機能を使用してアーカイブログを生成します。運用途中でprimary, standby両方のデータベースファイルが失われた場合であっても、継続的アーカイブが利用できるバックアップファイルがあれば、データベースファイルが失われる直前の状態のデータベースを再現することが出来ます。

【アーカイブログの削除】 ::
バックアップの取得にpg_basebackup を用いformat として plain (デフォルト設定)を指定した場合に限り 、アーカイブログの削除にpg-rex_archivefile_deleteが使用できます。それ以外の場合は『 <<_アーカイブログの削除_2,アーカイブログの削除>> 』にある説明を参照して、不要なアーカイブログを削除します。
+
NOTE: pg_basebackupについては、本マニュアルの『 <<_postgresqlのバックアップ,PostgreSQLのバックアップ>> 』にある操作例を参照

【バックアップファイルからのリストアとリカバリ】 ::
使用しているバックアップツールの定める手順にそって、バックアップファイルをリストアします。次いでPostgreSQL本体でリカバリすることでprimaryデータベースとして使用できるようになります。その際の注意事項は『 <<_primaryの起動,Primaryの起動>> 』にありますので参照してください。


=== アーカイブログの削除

本節では、PG-REX運用補助ツールを用いてデータベースの復旧に必要のないファイルをアーカイブディレクトリから削除する手順について記述します。

本節の作業はroot、もしくはPG-REXで管理しているDBクラスタを作成したユーザのみ実行可能です。

コマンドを直接実行してデータベースの復旧に必要のないファイルをアーカイブディレクトリから削除する手順については、『 <<_アーカイブログの削除_2,アーカイブログの削除>> 』を参照してください。


==== PostgreSQLアーカイブログの削除

運用を続けていくにしたがってアーカイブファイルの容量は増えていくため、継続的な運用のためには適宜削除を行う必要があります。 +
PostgreSQLのアーカイブログ(および付随するバックアップ履歴ファイル、タイムライン履歴ファイル)は、PrimaryおよびStandbyのリカバリに加え、『 <<_postgresqlのバックアップ,PostgreSQLのバックアップ>> 』の方法で取得したバックアップからのリカバリのいずれでも必要とならない場合に削除できます。 +
アーカイブログを削除したいノードで、pg-rex_archivefile_deleteコマンドを実行することで、これらの不要なファイルを自動的に判断し、削除または移動します。

[NOTE]
====
バックアップ履歴ファイルは、拡張子が.backupのファイルを指します。 +
https://www.postgresql.jp/document/18/html/continuous-archiving.html#BACKUP-BASE-BACKUP +
タイムライン履歴ファイルは、拡張子が.historyのファイルを指します。 +
https://www.postgresql.jp/document/18/html/continuous-archiving.html#BACKUP-TIMELINES
====

以下に、アーカイブログ削除の実行例を示します。

ここでは、保存すべき最古のベースバックアップを格納しているディレクトリを
/somewhere/basebackups/oldestとします。

[source,subs="normal"]
....
$ pg-rex_archivefile_delete -m /somewhere/basebackups/oldest

+**** 1. 実行準備 ****+
[red]*移動モードで実行します*
環境設定ファイル (pg-rex_tool.conf) を読み込みます
postgres@192.168.2.2's password:
パスワードが入力されました
両ノードの名前を取得します
cib.xml ファイルを読み込みます

+**** 2. WAL ファイル名の取得 ****+
指定されたバックアップからリカバリを行うために必要な最初の WAL ファイル名を取得します
"00000051000000010000003A"
自身のノード "pgrex01" の現時点の PGDATA "/dbfp/pgdata/data "からリカバリに必要な最初の WAL ファイル名を取得します
"00000052000000010000003E"
相手のノード "pgrex02" の現時点の PGDATA "/dbfp/pgdata/data "からリカバリに必要な最初の WAL ファイル名を取得します
"00000052000000010000003D"

+**** 3. 削除基準の算出 ****+
削除基準を "00000051000000010000003A" としました

+**** 4. アーカイブログの削除 ****+
削除対象のリストに "0000004F0000000100000035.00000020.backup"を追加します
削除対象のリストに "0000004D0000000100000034" を追加します
:(略)
移動先ディレクトリ "/dbfp/pgarch/arc1/yyyymmdd_HHMMSS"を作成しました
+-- 移動 -- 0000004F0000000100000035.00000020.backup+
:(略)
[red]*アーカイブログの移動に成功しました
移動モード実行のため、移動したファイルは"/dbfp/pgarch/arc1/yyyymmdd_HHMMSS" に格納されています*

※ ディレクトリ名は適宜読み替えてください。
....

この実行例ではコマンドに -mオプションを指定しているため、作業の終了後には
/dbfp/pgarch/arc1/yyyymmdd_HHMMSS
ディレクトリに不要となったファイルが格納されています。これを削除するか別のディスク等に移動させるなどすることで作業は完了します。 +
-m オプションの代わりに -r オプションを指定するとツール自身がファイルを削除します。


=== 計画的なノード切り替え

PrimaryとStandbyという2つのノードの役割を入れ替えることを、PG-REXではノード切り替えまたはスイッチオーバと呼びます。ここでは、PG-REX運用補助ツールのスイッチオーバ機能(pg-rex_switchover)を使用したノード切り替え手順を説明します。

本節の作業は、rootユーザで行います。

PG-REX運用補助ツールを使用せずに直接コマンドを実行してノード切り替えを実施したい場合は、『 <<_計画的なノード切り替え_2,計画的なノード切り替え>> 』を参照してください。

==== ノード切り替え

PG-REX運用補助ツールを使用したノード切り替えは、PG-REXのPrimaryとStandbyのどちらのノードでも実施することができます。以下に、pgrex01でノード切り替えを実行する場合の手順を示します。

. pg-rex_switchoverコマンドを実行します。パスワードの入力要求に対して、相手ノードのrootユーザのパスワードを入力してください。
+
....
# pg-rex_switchover
root@192.168.2.2's password:
パスワードが入力されました
....
+
. 表示された現在およびノード切り替え後のHAクラスタ状態を確認します。ノード切り替えを実行しても良い場合は[y]を入力します。 +
なお、ノード切り替え中は可用性が保証されないことに注意してください。
+
[source,subs="normal"]
....
+**** 実行準備 ****+
1. 環境設定ファイル (pg-rex_tools.conf)の読み込みと両ノードの名前を取得
[red]*+...+[OK]*
2. 現在およびノード切り替え後のHAクラスタ状態を確認

[ 現在 / ノード切り替え後のHAクラスタ状態 ]
+Primary : pgrex01 -> pgrex02+
[red]*+Standby : pgrex02 -> pgrex01+*

ノード切り替え中は可用性が保証されません
ノード切り替えを実行してもよろしいでしょうか？ (y/N) [red]*y*
....
+
. ノード切り替えが完了するまで待機し、コマンドが正常に完了したことを確認します。異常終了した場合は、HAクラスタ状態が不確定であり、データベースサービスが停止している可能性があります。この場合、元の状態への復旧は自動で実施されません。『 <<_故障対応,故障対応>> 』に従い、手動復旧を試みてください。
+
[source,subs="normal"]
....
+**** ノード切り替えを実行 ****+
3. Pacemaker の監視を停止
[red]*+...+[OK]*
4. Primary (pgrex01) の PostgreSQL を停止
[red]*+...+[OK]*
5. Pacemaker の監視を再開しノード切り替えを実行
[red]*+...+[OK]*
6. pgrex02 が新 Primary になったことを確認

+**** pgrex02 が Primary として起動しました ****+

7. pgrex01 の Pacemaker を停止
+Stopping Cluster (pacemaker)...+
+Stopping Cluster (corosync)...+
[red]*+...+[OK]*
8. pgrex01 で Standby を起動
00000011000000000000000C
00000012000000000000000E
00000013.history
+Starting Cluster...+

+**** pgrex01 が Standby として起動しました ****+

[red]*+***********************************+
+**** ノード切り替えが正常に完了しました ****+
+***********************************+

[ 現在のHAクラスタ状態 ]
 Primary : pgrex02
 Standby : pgrex01*
....

[CAUTION]
====
Pacemakerの監視を停止中(上記の4～6の間)にコマンドが異常終了した場合は、Pacemakerの監視が停止している可能性があるため、pcs statusコマンドを実行しHAクラスタ状態を確認してください。pcs statusコマンドの実行結果のリソース情報表示部に"unmanaged"が表示されている場合はPacemakerの監視が停止しています。Pacemakerの監視が停止している場合は、Pacemakerの監視を再開してください。
Pacemakerの監視を再開するには以下のコマンドを実行します。

....
# pcs property set maintenance-mode=
....
====

=== 計画的なメンテナンスのためのノードの停止、起動

本節では、PrimaryおよびStandbyの計画されたメンテナンス(PostgreSQLのマイナーバージョンアップやハードウェアの増設等の作業)を実施する時のノードの停止、メンテナンス後の起動の操作手順を記述します。 +
本節の作業は、rootユーザで実行します。

==== メンテナンスのためのノードの停止

メンテナンス対象のノードを停止する手順を以下に示します。

. メンテナンス対象のノードの停止
+
メンテナンス対象のノードの運用を停止します。停止手順については、『 <<_pg_rexの停止,PG-REXの停止>> 』を参照してください。
. データベースサービス継続の確認
+
起動中のノードでデータベースサービスが継続していることを、pcs statusコマンドを実行して確認します。
+
* ノード情報表示部で、起動中のノードの状態が"online"になっていること。
* リソース情報表示で、PG-REXリソース(pgsql-clone)に、"Promoted pgrex02"のように起動中のノードが表示されていること。
* リソース情報表示で、全てのIPaddr2リソース(ipaddr-primary、ipaddr-standby、ipaddr-replication)が、起動中のノードで稼働していること。

以下に、pgrex01停止後、pgrex02で確認した場合の例を示します。

[source,subs="quotes"]
....
# pcs status --full
：（略）
 * Last updated: _日時表示_ on pgrex02
：（略）

Node List:
  * Node pgrex01 (1): OFFLINE
  [red]** Node pgrex02 (2): online, feature set 3.20.1*
：（略）
  * Clone Set: pgsql-clone [pgsql] (promotable):
    * pgsql     (ocf:linuxhajp:pgsql):   [red]*Promoted pgrex02*
    * pgsql     (ocf:linuxhajp:pgsql):   Stopped
  * Resource Group: primary-group:
    * ipaddr-primary    (ocf:heartbeat:IPaddr2):         [red]*Started pgrex02*
    * ipaddr-replication        (ocf:heartbeat:IPaddr2):         [red]*Started pgrex02*
  * ipaddr-standby      (ocf:heartbeat:IPaddr2):         [red]*Started pgrex02*
：（略）
....

==== メンテナンス後のノードの起動

メンテナンス作業終了後は、メンテナンスのために停止したノードをStandbyとして起動します。起動手順については、『 <<_pg_rexの起動,PG-REXの起動>> 』を参照してください。

起動後、PrimaryとStandbyを切り替えたい場合は、『 <<_計画的なノード切り替え,計画的なノード切り替え>> 』に従い切り替えます。

<<<
