// Copyright (C) 2026, NTT, Inc.

=== アーカイブログの削除

本節では、コマンドを直接実行してデータベースの復旧に必要のないファイルをアーカイブディレクトリから削除する手順について記述します。 +
本節の作業はpostgresユーザで行います。

==== PostgreSQLアーカイブログの削除

運用を続けていくにしたがってアーカイブファイルの容量は増えていくため、継続的な運用のためには適宜削除を行う必要があります。 +
PostgreSQLのアーカイブログ、バックアップ履歴ファイル、タイムライン履歴ファイルは、以下の条件を全て満足する場合、アーカイブディレクトリから削除することができます。

*   管理している最古のバックアップ取得時点以前のファイル
*   Standbyが既に反映・チェックポイント済みのファイル

[NOTE]
====
バックアップ履歴ファイルは、拡張子が.backupのファイルを指します。 +
https://www.postgresql.jp/document/18/html/continuous-archiving.html#BACKUP-BASE-BACKUP

タイムライン履歴ファイルは、拡張子が.historyのファイルを指します。 +
https://www.postgresql.jp/document/18/html/continuous-archiving.html#BACKUP-TIMELINES
====

定期的に以下の手順に従って不要なファイルを削除します。

. 最古のバックアップに必要な最も古いWALファイル名を取得
+
最古のバックアップが存在するサーバで、最古のバックアップのbackup_labelファイルに記述されたSTART WAL LOCATIONの括弧内のWALファイル名を取得します。 +
ここでは管理する最古のバックアップの格納先を、$OLDEST_BACKUPとします。
+
[source, subs="normal"]
....
[~] $ cat $OLDEST_BACKUP/pgdata/backup_label
[red]*START WAL LOCATION:* 6A/4E0013D8 (file [red]*000000730000006A0000004E*)
CHECKPOINT LOCATION: 6A/4E002740
BACKUP METHOD: streamed
BACKUP FROM: primary
START TIME: _日時表示_
LABEL: pg_basebackup base backup
START TIMELINE: 73
....
+
. Standbyに必要な最も古いWALファイル名を取得
+
pgrex02で、pg_controldataを実行して、Standbyの"最終チェックポイントのREDO WALファイル"の値を取得します。
+
[source, subs="normal"]
....
[pgrex02] $ pg_controldata $PGDATA
：(略)
[red]*最終チェックポイントのREDO WALファイル:    000000750000006A00000051*
：(略)
....
+
. 削除対象の計算
+
1で取得した最古のバックアップに必要な最も古いWALファイル名と2で取得したStandbyに必要な最も古いWALファイル名を辞書順で比較します。その結果、小さいほうのWALファイル名を以降の手順で使用します。
+
. データベースの復旧に必要のないファイルの削除
+
両ノードで、削除対象の計算で決定したWALファイル名よりも古いアーカイブファイルを削除します。
+
以下のコマンドはpgrex01を想定した例になります。以下の手順をpgrex01で実行後、必ずpgrex02でも同じ手順を実行してください。
+
ls -lコマンドを用いてアーカイブディレクトリを辞書順にソートして出力します。このとき、削除対象の計算で決定したWALファイル名と同じ名前のファイルをチェックします。そのファイルより前に出力されたファイルを削除することができます。ただし、そのWALファイル名と先頭8桁が同じタイムライン履歴ファイルは削除しません。

.削除対象の例
====
削除対象の計算で「000000730000006A0000004E」と決定した場合、赤字が削除可能なファイルとなります。これらのファイルをrmコマンド等で削除してください。

[source, subs="normal"]
....
[pgrex01] $ ls -l /dbfp/pgarch/arc1
~ [red]*000000710000006A0000004B*
~ [red]*000000710000006A0000004B.00000020.backup*
~ [red]*00000072.history*
~ [red]*000000720000006A0000004C*
~ [red]*000000720000006A0000004D*
~ [red]*000000720000006A0000004E*
~ [red]*000000720000006A0000004F*
~ 00000073.history
~ [red]*000000730000006A0000004C*
~ [red]*000000730000006A0000004D*
~ 000000730000006A0000004E
~ 000000730000006A0000004E.000013D8.backup
~ 000000730000006A0000004F
~ 000000730000006A00000050
~ 00000074.history
~ 000000740000006A00000050
~ 000000740000006A00000051
~ 00000075.history
~ 000000750000006A00000051
....

====

