// Copyright (C) 2026, NTT, Inc.

=== 計画的なノード切り替え

本節では、手動による計画的なノード切り替えを実施する手順を記述します。

本節の作業は、rootユーザで行います。

==== ノード切り替え

手動によるノード切り替えの手順を以下に示します。ノード切り替えの手順はフェイルオーバとリソースの再組み込みの手順で構成されています。

. フェイルオーバ実行
+
pgrex01のPacemakerを停止し、Primaryをpgrex02に切り替えます。
+
. フェイルオーバ確認
+
pgrex02でpcs statusコマンドを実行し、以下を確認します。
+
* ノード情報表示で、pgrex01がOFFLINEとなっていること。
* pgsql-cloneリソースが、pgrex02上でPrimaryとして動作していること。
* ipaddr-primaryリソース、ipaddr-standbyリソースが、pgrex02上で起動していること。

+
[source, subs="normal"]
....
[pgrex02] # pcs status --full
：（略）
  * Last updated: _日時表示_ on pgrex02
  * Last change:  _日時表示_ by hacluster via crmd on pgrex01
：（略）

Node List:
  * [red]*Node pgrex01 (1): OFFLINE*
  * Node pgrex02 (2): online, feature set 3.20.1
：（略）
  * Clone Set: pgsql-clone [pgsql] (promotable):
    * pgsql     (ocf:linuxhajp:pgsql):   [red]*Promoted pgrex02*
    * pgsql     (ocf:linuxhajp:pgsql):   Stopped
  * Resource Group: primary-group:
    * ipaddr-primary    (ocf:heartbeat:IPaddr2):         Started [red]*pgrex02*
    * ipaddr-replication        (ocf:heartbeat:IPaddr2):         Started [red]*pgrex02*
  * ipaddr-standby      (ocf:heartbeat:IPaddr2):         Started pgrex02
：（略）
....  
+
. pgrex01の再組み込み準備
+
pgrex01の再組み込みの準備をします。再組み込みの準備には、pgrex02からベースバックアップの取得、pg_walの構成の修正、pgrex02のアーカイブログとの同期、起動禁止フラグの削除があります。
+
[source, subs="normal"]
....
[pgrex01] # su - postgres
最終ログイン: _日時表示_ pts/0
[pgrex01] $ rm -rf $PGDATA
[pgrex01] $ rm -rf /dbfp/pgwal/pg_wal
[pgrex01] $ pg_basebackup -h 192.168.2.3 -U repuser -D $PGDATA -X none -P
NOTICE:  all required WAL segments have been archived
70762/70762 kB (100%), 1/1 テーブル空間

※ -hにはレプリケーション受付用の仮想IPアドレス、
   -Uにはレプリケーションユーザを指定

[pgrex01] $ rsync -av --size-only 192.168.2.3:/dbfp/pgarch/arc1/ /dbfp/pgarch/arc1/
postgres@192.168.2.3's password:
receiving incremental file list
：（略）
sent 1,434 bytes  received 889,422,925 bytes  61,339,610.97 bytes/sec
total size is 889,200,754  speedup is 1.00

※ 接続先はレプリケーション受付用の仮想IPアドレス

[pgrex01] $ exit
ログアウト

[pgrex01] # rm /var/lib/pgsql/tmp/PGSQL.lock
....
+
. pgrex01の再組み込み
+
pgrex01をStandbyとして起動します。
+
. ノード切り替え確認
+
pgrex01でpcs statusコマンドを実行し、以下を確認します。
+
* ノード情報表示で、pgrex01がOnlineとなっていること。
* pgsql-cloneリソースが、pgrex01上でStandbyとして動作していること。
* ipaddr-replicationリソースが、pgrex01上で起動していること。

+
[source, subs="normal"]
....
[pgrex01] # pcs status --full
：（略）
  * Last updated: _日時表示_ on pgrex01
  * Last change:  _日時表示_ by hacluster via crmd on pgrex01
：（略）

Node List:
  * Node pgrex01 (1): online, feature set 3.20.1
  * Node pgrex02 (2): online, feature set 3.20.1
：（略）
  * Clone Set: pgsql-clone [pgsql] (promotable):
    * pgsql     (ocf:linuxhajp:pgsql):   [red]*Unpromoted pgrex01*
    * pgsql     (ocf:linuxhajp:pgsql):   [red]*Promoted pgrex02*
  * Resource Group: primary-group:
    * ipaddr-primary    (ocf:heartbeat:IPaddr2):         Started pgrex02
    * ipaddr-replication        (ocf:heartbeat:IPaddr2):         Started pgrex02
  * ipaddr-standby      (ocf:heartbeat:IPaddr2):         Started [red]*pgrex01*
  * Clone Set: ping-clone [ping]:
：（略）
Node Attributes:
  * Node: pgrex01 (1):
    * master-pgsql                      : 1000
    * pgsql-data-status                 : LATEST
    * pgsql-master-baseline             : 0000000005000060
    * pgsql-status                      : PRI
    * ping-status                       : 1
  * [red]*Node: pgrex02 (2):*
    * master-pgsql                      : [red]*100*
    * pgsql-data-status                 : [red]*STREAMING|SYNC*
    * pgsql-status                      : [red]*HS:sync*
    * ping-status                       : [red]*1*
：（略）
....  

