// Copyright (C) 2026, NTT, Inc.

=== PostgreSQL

本節では、PostgreSQLのインストールおよび基本設定について説明します。 +
この節を単独で実施する場合は、その準備として『 <<_インストール,インストール>> 』の1.を参照して、RHELのインストールDVDをマウントしてリポジトリに登録してください。 +
PostgreSQLのインストール完了後は、『 <<_インストール完了後作業,インストール完了後作業>> 』を参照して、準備前の状態に戻してください。


==== PostgreSQLのインストール

『PostgreSQLドキュメント』を参考にpgrex01とpgrex02へPostgreSQLをインストールします。PG-REXで使用できるPostgreSQLのバージョンは18のみとなります。 +
本作業はrootユーザで行います。 +
PG-REXのインストールに必須のRPMパッケージを以下に示します。

....
postgresql18-libs-18.1-1PGDG.rhel10.x86_64.rpm
postgresql18-18.1-1PGDG.rhel10.x86_64.rpm
postgresql18-server-18.1-1PGDG.rhel10.x86_64.rpm
postgresql18-contrib-18.1-1PGDG.rhel10.x86_64.rpm
postgresql18-docs-18.1-1PGDG.rhel10.x86_64.rpm

※ バージョンにあわせてファイル名は適宜読み替えてください。
※ PL/PerlやPL/Tclなどの各種言語インターフェイスが必要な場合は、それぞれに対応するパッケージをインストールしてください。
....

PostgreSQLをRPMパッケージからインストールします。

....
# dnf install postgresql18-libs-18.1-1PGDG.rhel10.x86_64.rpm postgresql18-18.1-1PGDG.rhel10.x86_64.rpm postgresql18-server-18.1-1PGDG.rhel10.x86_64.rpm postgresql18-contrib-18.1-1PGDG.rhel10.x86_64.rpm postgresql18-docs-18.1-1PGDG.rhel10.x86_64.rpm

※ バージョンにあわせてファイル名は適宜読み替えてください。
....

PostgreSQLのRPMパッケージをインストールすると「/usr/pgsql-18」にインストールされ、「postgres」というOSのユーザと、「postgres」というグループが作成されます。ただし、作成されたユーザにはパスワードの設定はされていません。また、同名のユーザまたはグループが存在する場合は、新規作成されません。 +
/var/lib/pgsqlのパーミッションは700に変更され、/var/lib/pgsql配下の全ファイルのオーナ、グループがpostgres、postgresに変更されます。 +
PG-REXではpostgresユーザのuidを26、postgresグループのgidを26であることを前提としています。以下のコマンドを実行し、postgresユーザが規定のuid、gidで作成されていることを確認します。

[source,subs="quotes"]
....
# id postgres
[red]*uid=26(postgres) gid=26(postgres) groups=26(postgres)*
....

規定のuid、gidになっていない場合は、下記のようにuid、gidを変更してください。

....
# groupmod -g 26 postgres
# usermod -u 26 postgres
# usermod -g 26 postgres
....

RPMのインストールにより新規でユーザが作成された場合は、パスワードを設定してください。

[source,subs="quotes"]
....
# passwd postgres
ユーザー postgres のパスワードを変更。
新しいパスワード:
新しいパスワードを再入力してください:
[red]*passwd: パスワードは正しく更新されました*
....

==== 環境変数の設定

pgrex01とpgrex02で/var/lib/pgsql/.bash_profileに環境変数を設定します。

* *PATH* : PostgreSQLコマンドへのパスの追加
* *PGDATA* : DBクラスタのパスの設定

pgrex01とpgrex02で同じ設定値を使用してください。 +
本作業はpostgresユーザで行います。

設定例を以下に示します。

[source,subs="quotes"]
....
[red]*export PATH=/usr/pgsql-18/bin:$PATH*
[red]*export PGDATA=/dbfp/pgdata/data*
....


==== DBクラスタ用ディレクトリの作成

pgrex01とpgrex02で、DBクラスタを格納するディレクトリとWALを格納するディレクトリ、アーカイブログを格納するディレクトリを以下の設定で作成します。 +
DBクラスタやWALを外付けストレージに配置する場合は、該当のディレクトリに外付けストレージの論理ディスクをマウントしてから実施します。 +
なお、ディレクトリが既に存在する場合は、ディレクトリを空にします。 +
本作業はrootユーザで行います。

.DBクラスタ用ディレクトリの設定
[cols="5",options="header"]
|===
|ディレクトリ
|パス
|所有者
|グループ
|権限

|DBクラスタ用
|/dbfp/pgdata/data
|postgres
|postgres
|700

|WAL用
|/dbfp/pgwal/pg_wal
|postgres
|postgres
|700

|アーカイブログ用
|/dbfp/pgarch/arc1
|任意
|任意
|postgres ユーザが読み書き可能な権限
|===

==== DBクラスタの初期化

pgrex01で、postgresユーザにてDBクラスタを初期化します。 +
本作業はpostgresユーザで行います。

....
$ initdb -D /dbfp/pgdata/data -X /dbfp/pgwal/pg_wal --encoding=UTF-8 --no-locale --data-checksums
....

==== postgresql.confの編集

pgrex01でpostgresql.confを編集します。PG-REXの動作に影響するPostgreSQLのパラメータの設定は本節で説明します。その他のパラメータの役割と設定については『PostgreSQLドキュメント』を参照してください。 +
本作業はpostgresユーザで行います。


以下にパラメータの設定例を示します。個々の設定については後述の説明を参照してください。

....
listen_addresses = '*'
superuser_reserved_connections = 10
password_encryption = scram-sha-256
wal_level = replica
synchronous_commit = on
archive_mode = always
archive_command = '/bin/cp %p /dbfp/pgarch/arc1/%f'
max_wal_senders = 10
wal_keep_size = 512MB
wal_sender_timeout = 20s
max_replication_slots = 10
hot_standby = on
max_standby_archive_delay = -1
max_standby_streaming_delay = -1
hot_standby_feedback = on
wal_receiver_timeout = 20s
restart_after_crash = off
....

設定値を決定するにあたって、注意すべき点を以下に示します。


* *listen_addresses*
+
PG-REXでは、StandbyからレプリケーションのためのIP接続を受け付けるため、そのアドレスを含むように設定する。
* *superuser_reserved_connections*
+
急用に余裕を持った値を設定しておく。10を推奨する。
* *password_encryption*
+
pg_hba.confのMETHODと合わせる必要がある。
* *wal_level*
+
logicalを設定することも可能。
* *synchronous_commit*
+
本マニュアルではレプリケーションの信頼性を重視するため、onを推奨する。remote_writeを設定した場合、故障発生時にデータを損失する可能性がある。remote_applyを設定した場合、on設定時と同様の信頼性となるが、トランザクションの応答時間が長くなる。
* *archive_mode*
+
設定はalways必須。
* *archive_command*
+
WALファイルを圧縮して保存したい場合のコマンド設定例を以下に示す。
+
....
'/bin/gzip -c %p > /dbfp/pgarch/arc1/%f.gz'
....
+
NOTE: gzipを使用する場合は、後述するリストアコマンドにもgzipを使用する必要があります。 +
リストアコマンドはpm_pcsgen環境定義書に設定します。設定方法は『 <<_postgresqlの設定,PostgreSQLの設定>> 』を参照してください。
+
* *max_wal_senders*
+
PG-REXでは、レプリケーション機能を利用するため、1以上を設定する必要がある。ただし、pg_basebackupによる運用中のバックアップ取得など、Standby以外からの接続に備え、余裕を持たせて設定することを推奨する。
* *wal_keep_size*
+
以下の点を考慮すること。
+
** 設定値が小さい場合、レプリケーション接続が一時的に切断されたときに、Standbyに転送されていないWALファイルがPrimaryから削除される可能性が高まる。WALファイルが削除されると、レプリケーションの再接続が不可能となる。
* *wal_sender_timeout*
+
Standbyの故障や両ノード間の通信断をPrimaryがすぐに検知できるように、タイムアウトを有効にすることを推奨する。postgresql.confで設定するTCP keepaliveに関する設定だけでは、検知に時間がかかることがあり、異常時のダウンタイムが長くなることがある。ただし、設定値が小さすぎると誤検知によりStandbyが切り離されることがあるため、設定値は事前検証等をして注意して決めること。
+
NOTE: TCP keepaliveに関する設定は、tcp_keepalives_idle、tcp_keepalives_interval、tcp_keepalives_countの設定を指します。
+
* *max_replication_slots*
+
pg_basebackupによるバックアップ取得などに備え、余裕を持たせて設定することを推奨する。
* *hot_standby*
+
設定はon必須。
* *max_standby_archive_delay*
+
PG-REXでは、Standbyの監視クエリがキャンセルされるのを回避するために、-1(キャンセルを無効)を設定する。
* *max_standby_streaming_delay*
+
PG-REXでは、Standbyの監視クエリがキャンセルされるのを回避するために、-1(キャンセルを無効)を設定する。
* *hot_standby_feedback*
+
設定はon必須。
* *wal_receiver_timeout*
+
wal_sender_timeoutと同程度に揃える必要がある。
* *restart_after_crash*
+
PG-REX運用中にPostgreSQLが自動的に再起動すると、Pacemakerによる状態管理の整合性が崩れるため、offを設定しなければならない。
+
* *設定してはいけないパラメータ*
+
PG-REXでは自動的に必要な設定を行うため、ユーザは以下のパラメータを設定してはならない。
+
** *primary_conninfo*
** *recovery_target_timeline*
** *restore_command*
** *synchronous_standby_names*

[IMPORTANT]
====
-Rオプション付きのpg_basebackupで取得したバックアップを使用する場合や、ALTER SYSTEMコマンドで上記項目の設定を行った場合、postgresql.auto.confに設定が記述されています。この場合、PG-REXが自動的に設定した内容が上書きされてしまうため、あらかじめALTER SYSTEMコマンドで項目を削除しておく必要があります。
====

==== レプリケーションユーザの作成

pgrex01で、PostgreSQLにレプリケーションのためのデータベースユーザを作成します。 +
本作業はpostgresユーザで行います。 +
データベースユーザ名とパスワードは適宜変更してください。

. PostgreSQLを一度起動します。
+
....
$ pg_ctl start
....
. createuserコマンドでレプリケーションユーザを作成します。
+
[source, subs="normal"]
....
$ createuser -l -P --replication repuser
新しいロールのためのパスワード: [red]*reppasswd*
もう一度入力してください：
....
+
. PostgreSQLを停止します。
+
....
$ pg_ctl stop
....

==== pg_hba.confの編集

pgrex01のpg_hba.confを編集して、PG-REXを構成するのに必要な設定を行います。 +
本作業はpostgresユーザで行います。

レプリケーション接続の設定については、pgrex02でも同じファイルを使用するため、両ノードのD-LANアドレスから接続を許可するように記述します。 +
レプリケーション接続以外の設定については『PostgreSQLドキュメント』を参照してください。

以下に、このマニュアルで想定している構成での記述例を示します。

....
# TYPE DATABASE    USER    ADDRESS        METHOD
host   replication repuser 192.168.2.1/32 scram-sha-256 // <1>
host   replication repuser 192.168.2.2/32 scram-sha-256 // <2>
....
<1> レプリケーション受付用の仮想IPアドレスの設定
<2> 相手のノードのD-LANのIPアドレスの設定

==== パスワードファイルの作成

PG-REX構成で使用するパスワードファイルを作成します。 +
本作業はpostgresユーザで行います。

pgrex01とpgrex02それぞれのpostgresユーザのホームディレクトリに、600の権限でパスワードファイル.pgpassを作成します。 +
PG-REXのレプリケーション接続および、PG-REX運用補助ツールで利用するため、レプリケーション受付用の仮想IPアドレス、および相手のノードのD-LANのIPアドレスについて記述します。

以下に、このマニュアルで想定している構成を前提とした記述例を示します。各フィールドの詳細な説明については『PostgreSQLドキュメント』を参照してください。

....
# hostname:port:database:username:password
192.168.2.3:5432:replication:repuser:reppasswd
192.168.2.2:5432:replication:repuser:reppasswd
....

<<<
